### ISSUE TITLE
[Bug] Not working in multiplayer.

### ISSUE THREAD

**Issue by 89gsc** [ignis05/baro-save-editor#6]
Tested both the online + downloaded tool. 

I backed up my save so no worries I still have it. 

When I decompress my save I want to remove an owned submarine (one of my badly made creations) from a campaign save.

I do this, compress, add it back to the server and when I load the campaign (from the server lobby) I get this error in console showing, I then see bot chatter as if I am in the game playing even though I am still in the lobby. 

![image](https://user-images.githubusercontent.com/1032459/191543365-1df28e91-af0c-4168-a1c4-900119f49930.png)

I put the original back and it loads fine. 

In terms of edits I made I basically remove the line entry for my sub manually or with the web editor button and resave it, so this line is what I removed: 

![image](https://user-images.githubusercontent.com/1032459/191544168-995cf397-5ed3-4111-b8ce-43ccb45c2a56.png)

Could you advise if I am missing something here or help at all, Really want to remove a sub from a campaign as it was a mistake making it. I have attached the original Save below: (this is before editing) 

[Bois Part 2.zip](https://github.com/ignis05/baro-save-editor/files/9618035/Bois.Part.2.zip)

I don't really know if there is a local save cache I need to clear off or what, this save was taken direct from the linux server itself.

**Comment by ignis05** [comment]
Sorry for the (very) late reply.
  
I recommend using the save editor for directly removing submarines in the future, instead of just decompressing the file and attempting to remove it manually. The built-in "delete submarine" option, apart from removing it from the list like you tried, also removes the attached submarine file from the save (the save stores file copies of all owned submarines).
![image](https://user-images.githubusercontent.com/48099798/211328288-6be6d4ea-acce-4193-ba02-59b5d813d685.png)
  
For me, it worked without issues on the savefile you provided.
![image](https://user-images.githubusercontent.com/48099798/211328423-209c6937-c972-4d4b-aa40-3ce50053b278.png)

I never tried to find out, what would happen if you just remove the submarine from the list, without removing its attached file, but I guess it would cause exactly what you were facing.
